routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')
    ->name('home');

Route::get('/profiles', 'MenuController@profiles')
    ->name('profiles');
Route::get('/berita', 'MenuController@berita')
    ->name('berita');
Route::get('/berita/ustyanto', 'MenuController@ustyanto')
    ->name('detail.ustyanto');
Route::get('/berita/beting-to-bening', 'MenuController@beting_to_bening')
    ->name('detail.beting_to_bening');
Route::get('/berita/training-imam-dan-khatib', 'MenuController@training_imam_dan_khatib')
    ->name('detail.training_imam_dan_khatib');
Route::get('/gambar', 'MenuController@gambar')
    ->name('gambar');
Route::get('/kontak', 'MenuController@kontak')
    ->name('kontak');
Route::post('/kontak/store', 'MenuController@store');
Route::post('/kontak/stores', 'MenuController@stores');

Route::group(['middleware' => 'auth'], function () {

    Route::get('/kegiatan', 'KegiatanController@input')
        ->name('kegiatan_input');;

    Route::post('/kegiatan/store', 'KegiatanController@store');

    Route::resource(
        'kegiatans',
        'KegiatanController',
        ['except' => ['create']]
    );

    Route::get('/mualaf', 'MualafController@input')
        ->name('mualaf');

    Route::post('/mualaf/create', 'MualafController@create');

    Route::resource(
        'mualafs',
        'MualafController',
        ['except' => ['create']]
    );

    Route::get('/getDistricts/{id}', 'KegiatanController@getDistricts');

    Route::get('/getVillages/{id}', 'KegiatanController@getVillages');



    Route::get('/profile', 'ProfileController@edit')
        ->name('profile.edit');

    Route::patch('/profile', 'ProfileController@update')
        ->name('profile.update');

    Route::get('password', 'PasswordController@edit')
        ->name('user.password.edit');

    Route::patch('password', 'PasswordController@update')
        ->name('user.password.update');

    Route::get('dashboard', 'DashboardController@index')
        ->name('dashboard.index');

    Route::get('kegiatan/export-excel/', 'KegiatanController@export_excel');
    Route::get('mualaf/export-excel/', 'MualafController@export_excel');
});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function () {
    Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});

// admin
Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('pesan', 'PesanController');
        Route::get('dai', 'UsersController@dai')
            ->name('dai.index');
        Route::get('/dai/{user}/ubah', 'UsersController@ubah')->name('dai.ubah');
        Route::put('/dai/simpan/{user}', 'UsersController@simpan')->name('dai.simpan');
        Route::get('/dai/detail/{user}', 'UsersController@detail')->name('dai.detail');
        Route::delete('/dai/delete/{user}', 'UsersController@delete')->name('dai.delete');

        Route::resource('role', 'RoleController');
    });

Auth::routes(['verify' => true]);

app/Mualaf.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mualaf extends Model
{
    // use SoftDeletes;

    protected $fillable = [
        'jml_mualaf', 'deskripsi',  'tgl', 'users_id', 'date', 'month', 'year'
    ];

    // 'alamat', 'id_kab', 'id_kec', 'id_desa',

    // protected $hidden = [];

    public function user()
    {
        return $this->belongsTo(User::class, 'users_id', 'id');
    }

    // public function kab()
    // {
    //     return $this->belongsTo(Reg_regencies::class, 'id_kab', 'id');
    // }

    // public function kec()
    // {
    //     return $this->belongsTo(Reg_districts::class, 'id_kec', 'id');
    // }

    // public function desa()
    // {
    //     return $this->belongsTo(Reg_villages::class, 'id_desa', 'id');
    // }

    public function fotos()
    {
        return $this->hasMany(MualafDetail::class, 'mualafs_id', 'id');
    }
}

app/Http/Controllers/MualafController.php
<?php

namespace App\Http\Controllers;

use App\Mualaf;
use App\MualafDetails;
use App\Http\Controllers\Controller;
use App\MualafDetail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Reg_regencies;
use App\Reg_districts;
use App\Reg_villages;
use App\User;
use Illuminate\Support\Facades\DB;

use App\Exports\MualafsExport;
use Maatwebsite\Excel\Facades\Excel;


class MualafController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    // bagian LMS
    public function input(Request $request)
    {
        $departmentData['data'] = Reg_regencies::orderby("name", "asc")
            ->select('id', 'name')
            ->get();

        return view('pages.mualaf.index')->with("departmentData", $departmentData);
    }

    public function getDistricts($departmentid = 0)
    {

        // Fetch Employees by Departmentid
        $empData['data'] = Reg_districts::orderby("name", "asc")
            ->select('id', 'name')
            ->where('regency_id', $departmentid)
            ->get();

        return response()->json($empData);
    }

    public function getVillages($distid = 0)
    {

        // Fetch Employees by distid
        $distData['data'] = Reg_villages::orderby("name", "asc")
            ->select('id', 'name')
            ->where('district_id', $distid)
            ->get();

        return response()->json($distData);
    }

    public function create(Request $request)
    {
        $expiry = explode("/", $request->tgl);

        $date = $expiry[0];
        $month = $expiry[1];
        $year = $expiry[2];

        $lastid = Mualaf::create([
            'users_id' => Auth::user()->id,
            'jml_mualaf' => $request->jml_mualaf,
            'deskripsi' => $request->deskripsi,
            // 'alamat' => $request->alamat,
            // 'id_kab' => $request->id_kab,
            // 'id_kec' => $request->id_kec,
            // 'id_desa' => $request->id_desa,
            'tgl' => $request->tgl,
            'date' => $date,
            'month' => $month,
            'year' => $year
        ])->id;

        $this->validate($request, [
            'foto' => 'required',
            'foto.*' => 'mimes:jpeg,jpg,png|max:2000'
        ]);

        $files = [];
        foreach ($request->file('foto') as $file) {
            $path = $file->store('public/ktp');
            $files[] = [
                'mualafs_id' => $lastid,
                'nama' => $request->nama,
                'alamat' => $request->alamat,
                'foto' => $file->getClientOriginalName()
            ];
        }
        MualafDetail::insert($files);

        session()->flash('sukses', 'Data berhasil di Input');
        return redirect('/mualaf');
    }

    // bagian CMS
    public function index()
    {
        $user_id = Auth::user()->role_id;
        if ($user_id == 1) {
            $items = Mualaf::with([
                'user'
            ])->get();
            return view('pages.cms.mualaf.index', [
                'items' => $items
            ]);
        } elseif ($user_id == 2) {
            $items = Mualaf::with([
                'user'
            ])->where('users_id', '=', Auth::user()->id)
                ->get();
            return view('pages.cms.mualaf.index', [
                'items' => $items
            ]);
        }
    }

    public function show(Mualaf $mualaf)
    {
        $user = User::all();
        // $kab = Reg_regencies::all();
        // $kec = Reg_districts::all();
        // $desa = Reg_villages::all();
        $mualafs = MualafDetail::all();

        return view('pages.cms.mualaf.detail', [
            'mualaf' => $mualaf,
            'mualafs' => $mualafs,
            // 'kab' => $kab,
            // 'desa' => $desa,
            // 'kec' => $kec,
            'user' => $user
        ]);
    }

    public function edit(Mualaf $mualaf)
    {
        $user_id = Auth::user()->role_id;
        if ($user_id == 1) {
            $user = User::all();
            $kab = Reg_regencies::all();
            $kec = Reg_districts::all();
            $desa = Reg_villages::all();
            return view('pages.cms.mualaf.edit', [
                'mualaf' => $mualaf,
                // 'kab' => $kab,
                // 'desa' => $desa,
                // 'kec' => $kec,
                'user' => $user
            ]);
        } else {
            return abort(404);
        }
    }

    public function update(Request $request, Mualaf $mualaf)
    {
        $this->validate($request, [
            'tgl' => 'required',
            'jml_mualaf' => 'required|numeric',
            'deskripsi' => 'required',
            // 'alamat' => 'required',
            // 'id_kab' => 'required',
            // 'id_kec' => 'required',
            // 'id_desa' => 'required',
        ]);

        $mualaf->tgl = $request->tgl;
        $mualaf->jml_mualaf = $request->jml_mualaf;
        $mualaf->deskripsi = $request->deskripsi;
        // $mualaf->alamat = $request->alamat;
        // $mualaf->id_kab = $request->id_kab;
        // $mualaf->id_kec = $request->id_kec;
        // $mualaf->id_desa = $request->id_desa;
        $mualaf->save();

        if ($mualaf->save()) {
            $request->session()->flash('sukses', 'Data berhasil di Ubah');
        } else {
            $request->session()->flash('error', 'has been error updated');
        }
        session()->flash('sukses', 'Data Mualaf berhasil edit');
        return redirect(route('mualafs.index'));
    }

    public function destroy(Mualaf $mualaf)
    {
        $user_id = Auth::user()->role_id;
        if ($user_id == 1) {
            $mualaf->delete();
            session()->flash('sukses', 'Data berhasil dihapus');
            return redirect()->route('mualafs.index');
        } else {
            return abort(404);
        }
    }

    public function export_excel()
    {
        return Excel::download(new MualafsExport, 'Data Mualaf 2021.xlsx');
    }
}

resources/views/pages/cms/mualaf/detail.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container-fluid">
        <div class="row mt-12">
            <div class="col md-5">
                <div class="card-deck">
                    <div class="col-xl-12 col-md-8 mb-5">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                                        <h3 class="h3 mb-0 text-gray-800">Detail Mualaf</h3>
                                    </div>
                                    <!-- Content Row -->
                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                    <table class="table table-bordered">
                                        <tr>
                                            <th>Nama Ustadz</th>
                                            <td>{{ $mualaf->user->username }}<b>
                                        </tr>
                                        <tr>
                                            <th>Nomor Handphone</th>
                                            <td>{{ $mualaf->user->nohp }}<b>
                                        </tr>
                                        <tr>
                                            <th>Alamat Ustadz</th>
                                            <td>{{ $mualaf->user->alamat }}<b>
                                        </tr>
                                        <tr>
                                            <th>Tanggal</th>
                                            <td>{{ $mualaf->tgl }}</td>
                                        </tr>
                                        <tr>
                                            <th>Jumlah Mualaf</th>
                                            <td class="text-orange">{{ $mualaf->jml_mualaf }}</td>
                                        </tr>
                                        {{-- <tr>
                                            <th>Alamat</th>
                                            <td class="lower">{{ $mualaf->alamat }}. <br>
                                                {{ $mualaf->desa->name }}. {{ $mualaf->kec->name }}.
                                                {{ $mualaf->kab->name }}</td>
                                        </tr> --}}
                                        <tr>
                                            <th width="25%">Keterangan</th>
                                            <td>{{ $mualaf->deskripsi }}</td>
                                        </tr>
                                        <tr>
                                            <th>Data Mualaf</th>
                                            <td>
                                                <table class="table table-bordered">
                                                    <tr>
                                                        <th>No</th>
                                                        <th>Nama</th>
                                                        <th>Alamat</th>
                                                        <th>Foto KTP</th>
                                                    </tr>
                                                    @php $no = 1; @endphp
                                                    @foreach ($mualaf->fotos as $detail)
                                                        <tr>
                                                            <td>{{ $no++ }}</td>
                                                            <td>{{ $detail->nama }}</td>
                                                            <td>{{ $detail->alamat }}</td>
                                                            <td>
                                                                <div style="width: 25rem;">
                                                                    <img src="{{ Storage::url('/dokumentasi/' . $detail->foto) }}"
                                                                        class="img-thumbnail"><br>{{ $detail->foto }}
                                                                    <div class="card-body">
                                                                        <h6 class="card-title text-center">
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/cms/mualaf/edit.blade.php
@extends('layouts.admin')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- Content Row -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row mt-12">
            <div class="col md-5">
                <div class="card-deck">
                    <div class="col-xl-12 col-md-8 mb-5">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="modal-body">
                                        <h3 class="h3 mb-4 text-gray-800">Edit Data</h3>
                                        <hr>
                                        <form method="POST" action="{{ route('mualafs.update', $mualaf->id) }}">
                                            @method('PUT')
                                            @csrf
                                            <div class="form-group row">
                                                <label for="tgl" class="col-sm-2 col-form-label">Tanggal</label>
                                                <div class="col-sm-10">
                                                    <input id="tgl" type="text"
                                                        class="form-control datepicker @error('tgl') is-invalid @enderror"
                                                        name="tgl" value="{{ old('tgl', $mualaf->tgl) }}"
                                                        autocomplete="tgl" autofocus>
                                                    @error('tgl')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label for="jml_mualaf" class="col-sm-2 col-form-label">Jumlah
                                                    Mualaf</label>
                                                <div class="col-sm-10">
                                                    <input id="jml_mualaf" type="number" class="form-control"
                                                        name="jml_mualaf"
                                                        value="{{ old('jml_mualaf', $mualaf->jml_mualaf) }}"
                                                        autocomplete="jml_mualaf" autofocus>
                                                    @error('jml_mualaf')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label for="deskripsi" class="col-sm-2 col-form-label">Keterangan</label>
                                                <div class="col-sm-10">
                                                    <textarea name="deskripsi" cols="20" rows="5"
                                                        class="form-control @error('deskripsi') is-invalid @enderror"
                                                        name="deskripsi"
                                                        autofocus>{{ old('deskripsi', $mualaf->deskripsi) }}</textarea>
                                                    @error('deskripsi')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                            {{-- <div class="form-group row">
                                                <label for="alamat" class="col-sm-2 col-form-label">Alamat</label>
                                                <div class="col-sm-10">
                                                    <input id="alamat" type="text"
                                                        class="form-control @error('alamat') is-invalid @enderror"
                                                        name="alamat" value="{{ old('alamat', $mualaf->alamat) }}"
                                                        autocomplete="alamat" autofocus>
                                                    @error('alamat')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div> --}}
                                            {{-- <div class="row form-group">
                                                <label class="col-sm-2 col-form-label">Pilih Kabupaten/Kota</label>
                                                <div class="col-sm-10">
                                                    <select class="form-control" id='sel_depart' name="id_kab">
                                                        @foreach ($kab as $kabs)
                                                            <option value="{{ $kabs->id }}"
                                                                {{ $kabs->id == $mualaf->id_kab ? 'selected' : '' }}>
                                                                {{ $kabs->name }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <label class="col-sm-2 col-form-label">Pilih Kecamatan</label>
                                                <div class="col-sm-10">
                                                    <select class="form-control" name="id_kec" id='sel_emp'>
                                                        @foreach ($kec as $kecs)
                                                            <option value="{{ $kecs->id }}"
                                                                {{ $kecs->id == $mualaf->id_kec ? 'selected' : '' }}>
                                                                {{ $kecs->name }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <label class="col-sm-2 col-form-label">Pilih Kelurahan/Desa</label>
                                                <div class="col-sm-10">
                                                    <select class="form-control" name="id_desa" id='sel_vil'>
                                                        @foreach ($desa as $desas)
                                                            <option value="{{ $desas->id }}"
                                                                {{ $desas->id == $mualaf->id_desa ? 'selected' : '' }}>
                                                                {{ $desas->name }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div> --}}
                                            <div class="form-file row justify-content-end">
                                                <div class="col-sm-10">
                                                    <button type="submit" class="btn btn-primary btn-block">Simpan</button>
                                                </div>
                                            </div>

                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/pages/cms/mualaf/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
        @if (session()->has('sukses'))
            <div class="alert alert-info col-xl-12 alert-dismissible fade show" role="alert">
                {{ session()->get('sukses') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="card border-left-primary shadow mb-4">
            <div class="card-header py-3">
                <div class="d-sm-flex align-items-center justify-content-between">
                    <h5 class="m-0 font-weight-bold text-gray-800">Data Mualaf</h5>
                    @if (Auth::user()->role_id == 1)
                        <a href="{{ url('/mualaf/export-excel') }}" class="btn btn-sm btn-success btn-export"
                            style="color: #fff"><i class="far fa-file-excel"></i>
                            &nbsp;Export Excel</a>
                    @else
                    @endif
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama Ustadz</th>
                                <th>Tanggal</th>
                                <th>Jum Mualaf</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp
                            @forelse($items as $item)
                                <tr>
                                    <td>{{ $no++ }}</td>
                                    <td>{{ $item->user->username }}</td>
                                    <td>{{ $item->tgl }}</td>
                                    <td>{{ $item->jml_mualaf }}</td>
                                    <td>
                                        <a href="{{ route('mualafs.show', $item->id) }}" class="btn btn-sm btn-primary">
                                            <i class="fa fa-search-plus"></i>
                                        </a>
                                        @if (Auth::user()->role_id == 1)
                                            <a href="{{ route('mualafs.edit', $item->id) }}" class="btn btn-sm btn-info">
                                                <i class="fa fa-pencil-alt"></i>
                                            </a>
                                            <form action="{{ route('mualafs.destroy', $item->id) }}" method="post"
                                                class="d-inline">
                                                @csrf
                                                @method('delete')
                                                <button class="btn btn-sm btn-danger">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        @else
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <td colspan="7" class="text-center">
                                    Data Kosong
                                </td>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection